# =============================================================================
#  frdm_env_monitor — prj.conf
#  NXP FRDM-MCXN947  |  Zephyr RTOS
# =============================================================================

# ── Kernel ────────────────────────────────────────────────────────────────────
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=8192

# ── Multithreading ────────────────────────────────────────────────────────────
CONFIG_MULTITHREADING=y

# ── Logging ───────────────────────────────────────────────────────────────────
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

# ── I2C (BME680) ──────────────────────────────────────────────────────────────
CONFIG_I2C=y

# ── SPI (LIS3DH) ─────────────────────────────────────────────────────────────
CONFIG_SPI=y

# ── I3C (P3T1755DP) ──────────────────────────────────────────────────────────
CONFIG_I3C=y

# ── Drivers de sensor ─────────────────────────────────────────────────────────
CONFIG_SENSOR=y
CONFIG_BME680=y
CONFIG_LIS3DH=y

# ── GPIO (RGB LED, touch slider) ──────────────────────────────────────────────
CONFIG_GPIO=y

# ── PWM (LED RGB via PWM) ────────────────────────────────────────────────────
CONFIG_PWM=y
CONFIG_LED=y

# ── ADC (touch slider via ADC capacitivo) ────────────────────────────────────
CONFIG_ADC=y

# ── Printk / shell ────────────────────────────────────────────────────────────
CONFIG_PRINTK=y
CONFIG_CBPRINTF_FP_SUPPORT=y
